#**Data Analysis in Book Trend**

In [841]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [842]:
df= pd.read_csv('books.csv')
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,url,bullet_1,bullet_2,bullet_3,bullet_4,bullet_5,bullet_6,bullet_7,bullet_8,bullet_9,bullet_10,bullet_11,bullet_12
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,https://atlanticbooks.com/collection...,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,(2),• Author(s): Clear | James • Publish...,Quick shop,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,https://atlanticbooks.com/collection...,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Hector Garcia • Publish...,Quick shop,NaN,NaN
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,https://atlanticbooks.com/collection...,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,(1),• Author(s): Ichiro Kishimi • Publis...,View full details,Quick shop
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,https://atlanticbooks.com/collection...,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Chetan Bhagat • Publish...,View full details,Quick shop,NaN
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,https://atlanticbooks.com/collection...,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Brianna Wiest • Publish...,View full details,Quick shop,NaN

In [843]:
df.drop(columns=['url'], inplace=True)

In [844]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_1,bullet_2,bullet_3,bullet_4,bullet_5,bullet_6,bullet_7,bullet_8,bullet_9,bullet_10,bullet_11,bullet_12
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,(2),• Author(s): Clear | James • Publish...,Quick shop,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Hector Garcia • Publish...,Quick shop,NaN,NaN
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,(1),• Author(s): Ichiro Kishimi • Publis...,View full details,Quick shop
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Chetan Bhagat • Publish...,View full details,Quick shop,NaN
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Brianna Wiest • Publish...,View full details,Quick shop,NaN

In [845]:
df.drop(columns=["bullet_1", "bullet_2", "bullet_3", "bullet_4", "bullet_5", "bullet_6","bullet_7", "bullet_8"], inplace=True)

In [846]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9                                bullet_10          bullet_11   bullet_12
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5                                      (2)  • Author(s): Clear | James • Publish...         Quick shop         NaN
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...                               Quick shop                NaN         NaN
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0                                      (1)  • Author(s): Ichiro Kishimi • Publis...  View full details  Quick shop
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...                        View full details         Quick shop         NaN
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...                        View full details         Quick shop         NaN

In [847]:
df[~df["bullet_12"].isna()]

     page                                    title                       writer     format actual_price price_before_discount  discount_percent  stars bullet_9                                bullet_10          bullet_11   bullet_12
2       1  The Courage To Be Disliked How To Fr...               Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0      (1)  • Author(s): Ichiro Kishimi • Publis...  View full details  Quick shop
5       1  The Art of Spending Money: Simple Ch...                Morgan Housel  Paperback         ₹290                  ₹499              42.0    5.0      (1)  • Author(s): Morgan Housel • Publish...  View full details  Quick shop
25      1                     The 48 Laws Of Power               Greene, Robert  Paperback         ₹650                  ₹999              35.0    5.0      (1)  • Author(s): Greene, Robert • Publis...  View full details  Quick shop
44      1             Heart Lamp: Selected Stories  Banu Mushtaq, Deepa Bhasthi  Paperback         ₹260                  ₹399              35.0    3.0      (3)  • Author(s): Banu Mushtaq | Deepa Bh...  View full details  Quick shop
211     4  Hindus in Hindu Rashtra: Eighth-Clas...            Anand Ranganathan  Hardcover         ₹260                  ₹399              35.0    5.0      (1)  • Author(s): Anand Ranganathan • Pub...  View full details  Quick shop
250     5  Life's Amazing Secrets (Hindi): Jeev...               Gaur Gopal Das  Paperback         ₹163                  ₹250              35.0    5.0      (1)  • Author(s): Gaur Gopal Das • Publis...  View full details  Quick shop
331     6  The World's Favourite: And Then Ther...               Arthur W Gross  Boxed Set         ₹715                ₹1,099              35.0    NaN        /  • Author(s): Arthur W Gross • Publis...  View full details  Quick shop
501     9                 The Master And Margarita             Mikhail Bulgakov  Paperback         ₹325                  ₹499              35.0    5.0      (1)  • Author(s): Mikhail Bulgakov • Publ...  View full details  Quick shop
542    10         The Chronicles of Narnia Box Set                  C. S. Lewis        NaN       ₹4,731                ₹6,712              30.0    NaN        /  • Author(s): C. S. Lewis • Publisher...  View full details  Quick shop
555    10  Apprenticed to a Himalayan Master: A...                        Sri M  Paperback         ₹325                  ₹499              35.0    5.0      (1)  • Author(s): Sri M • Publisher: Indi...  View full details  Quick shop
560    10  The Hobbit & The Lord of the Rings B...             J. R. R. Tolkien  Boxed Set       ₹1,540                ₹2,199              30.0    NaN        /  • Author(s): J. R. R. Tolkien • Publ...  View full details  Quick shop
612    11  A Court of Thorns and Roses Paperbac...                Sarah J. Maas  Paperback       ₹2,145                ₹3,299              35.0    NaN        /  • Author(s): Sarah J. Maas • Publish...  View full details  Quick shop
636    11   A Game of Thrones: The Story Continues           George R.R. Martin        NaN       ₹5,916                ₹7,910              25.0    NaN        /  • Author(s): George R.R. Martin • Pu...  View full details  Quick shop
677    12                Yuval Noah Harari Box Set            Yuval Noah Harari        NaN       ₹1,300                ₹1,999              35.0    NaN        /  • Author(s): Yuval Noah Harari • Pub...  View full details  Quick shop
704    12                         Valmiki Ramayana                 Bibek Debroy  Hardcover       ₹1,170                ₹1,799              35.0    5.0      (1)  • Author(s): Bibek Debroy • Publishe...  View full details  Quick shop
722    13  The Adventures of Feluda (Special Bi...                 Satyajit Ray        NaN       ₹1,235                ₹1,899              35.0    NaN        /  • Author(s): Satyajit Ray • Publishe...  View full details  Quick shop
768    13                    Shatter Me Collection                 Tahereh Mafi        NaN       ₹2,730                ₹4,199              35.0    NaN        /  • Author(s): Tahereh Mafi • Publishe...  View full details  Quick shop
771    13  From Gods To The God Christianizatio...                  Rama Seshan        NaN         ₹650                  ₹999              35.0    NaN        /  • Author(s): Rama Seshan • Publisher...  View full details  Quick shop
788    14                    Once there was a boy…               Oliver Jeffers        NaN       ₹1,170                ₹1,799              35.0    NaN        /  • Author(s): Oliver Jeffers • Publis...  View full details  Quick shop
865    15            The Travelling Cat Chronicles                 Hiro Arikawa  Paperback         ₹455                  ₹699              35.0    5.0      (1)  • Author(s): Hiro Arikawa • Publishe...  View full details  Quick shop
941    16  The Brothers Karamazov: A Novel in F...           Fyodor Dostoyevsky  Paperback         ₹390                  ₹599              35.0    5.0      (1)  • Author(s): Fyodor Dostoyevsky • Pu...  View full details  Quick shop

In [848]:
mask = df["bullet_12"].notna()

df.loc[mask, "bullet_9"] = df.loc[mask, "bullet_10"]
df.loc[mask, "bullet_10"] = df.loc[mask, "bullet_11"]
df.loc[mask, "bullet_11"] = df.loc[mask, "bullet_12"]
df.loc[mask, "bullet_12"] = None

In [849]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9                                bullet_10   bullet_11 bullet_12
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5                                      (2)  • Author(s): Clear | James • Publish...  Quick shop       NaN
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...                               Quick shop         NaN       NaN
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...                        View full details  Quick shop       NaN
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...                        View full details  Quick shop       NaN
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...                        View full details  Quick shop       NaN

In [850]:
df["bullet_12"].isna().sum()

np.int64(945)

In [851]:
df.size

11340

In [852]:
df.shape

(945, 12)

In [853]:
df.drop(columns=["bullet_12"], inplace=True)

In [854]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9                                bullet_10   bullet_11
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5                                      (2)  • Author(s): Clear | James • Publish...  Quick shop
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...                               Quick shop         NaN
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...                        View full details  Quick shop
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...                        View full details  Quick shop
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...                        View full details  Quick shop

In [855]:
df["bullet_11"].value_counts()

bullet_11
Quick shop    528
Name: count, dtype: int64

In [856]:
df["bullet_11"].isnull().sum()

np.int64(417)

In [857]:
df.drop(columns=["bullet_11"], inplace=True)

In [858]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9                                bullet_10
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5                                      (2)  • Author(s): Clear | James • Publish...
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...                               Quick shop
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...                        View full details
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...                        View full details
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...                        View full details

In [859]:
df["bullet_10"].value_counts()

bullet_10
View full details                                                                                                                                                      514
Quick shop                                                                                                                                                             416
• Author(s): J. K. Rowling • Publisher: Bloomsbury Publishing PLC • Publisher Imprint: Bloomsbury Publishing PLC                                                         3
• Author(s): Blyton, Enid • Publisher: Hachette Childrens Group • Publisher Imprint: Hodder Children'S Books                                                             2
• Author(s): Clear | James • Publisher: Penguin • Publisher Imprint: Penguin Random House • Subject: General Books                                                       1
• Author(s): Satoshi Yagisawa • Publisher: Bonnier Books Ltd • Publisher Imprint: Bonnier Books Ltd                                                                      1
• Author(s): Kun (UNESCO-IHE Institute for Water Education, Delft, The Netherlands) Yan • Publisher: Simon & Schuster Ltd • Publisher Imprint: Simon & Schuster Ltd      1
• Author(s): Ladybird • Publisher: Penguin Random House Children's UK • Publisher Imprint: Penguin Random House Children's UK                                            1
• Author(s): Rick Riordan • Publisher: MIXGD • Publisher Imprint: MIXGD • Subject: Children Books                                                                        1
• Author(s): Brandon Sanderson • Publisher: Orion Publishing Co • Publisher Imprint: Orion Publishing Co • BISAC: Fantasy - Contemporary                                 1
• Author(s): Jennifer Lynn Barnes • Publisher: Hachette Children's Group • Publisher Imprint: Hachette Children's Group                                                  1
• Author(s): Lauren Roberts • Publisher: Simon & Schuster Ltd • Publisher Imprint: Simon & Schuster Ltd                                                                  1
• Author(s): Tahereh Mafi • Publisher: HarperCollins Publishers • Publisher Imprint: HarperCollins Publishers • BISAC: Action & Adventure - General                      1
Name: count, dtype: int64

In [860]:
mask = df["bullet_10"].str.contains("author", case=False, na=False)

df.loc[mask, "bullet_9"] = df.loc[mask, "bullet_10"]
df.loc[mask, "bullet_10"] = None

In [861]:
df["bullet_10"].value_counts()

bullet_10
View full details    514
Quick shop           416
Name: count, dtype: int64

In [862]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9          bullet_10
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...                NaN
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...         Quick shop
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...  View full details
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...  View full details
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...  View full details

In [863]:
df.drop(columns=["bullet_10"], inplace=True)

In [864]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...

In [865]:
df

     page                                    title                writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9
0       1               Atomic Habits (Lead Title)          Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...
1       1                                   Ikigai         Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...
2       1  The Courage To Be Disliked How To Fr...        Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...
3       1        12 Years: My Messed-up Love Story         Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...
4       1  The Mountain Is You: Transforming Se...         Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...
..    ...                                      ...                   ...        ...          ...                   ...               ...    ...                                      ...
940    16  Anansi Helps a Friend: Read It Yours...              Ladybird  Hardcover         ₹228                  ₹350              35.0    NaN  • Author(s): Ladybird • Publisher: L...
941    16  The Brothers Karamazov: A Novel in F...    Fyodor Dostoyevsky  Paperback         ₹390                  ₹599              35.0    5.0  • Author(s): Fyodor Dostoyevsky • Pu...
942    16                The Count of Monte Cristo  Alexandre Dumas Pere  Paperback         ₹390                  ₹599              35.0    NaN  • Author(s): Alexandre Dumas Pere • ...
943    16                            Vishnu Purana          Bibek Debroy  Paperback         ₹390                  ₹599              35.0    NaN  • Author(s): Bibek Debroy • Publishe...
944    16  Food Intelligence: A comprehensive b...        PhD Kevin Hall  Paperback         ₹520                  ₹799              35.0    NaN  • Author(s): PhD Kevin Hall • Publis...

[945 rows x 9 columns]

In [866]:
df["bullet_9"].value_counts()

bullet_9
• Author(s): Shannon Messenger • Publisher: Simon & Schuster Ltd • Publisher Imprint: Simon & Schuster Ltd                                                                                                                                                   7
• Author(s): Tahereh Mafi • Publisher: HarperCollins Publishers • Publisher Imprint: HarperCollins Publishers                                                                                                                                                6
• Author(s): J. K. Rowling • Publisher: Bloomsbury Publishing PLC • Publisher Imprint: Bloomsbury Publishing PLC                                                                                                                                             5
• Author(s): Julia Donaldson • Publisher: Pan Macmillan • Publisher Imprint: Pan Macmillan                                                                                                                                                                   5
• Author(s): Ladybird • Publisher: Penguin Random House Children's UK • Publisher Imprint: Penguin Random House Children's UK                                                                                                                                5
                                                                                                                                                                                                                                                            ..
• Author(s): Ladybird • Publisher: Ladybird • Publisher Imprint: Ladybird • BISAC: Readers - BeginnerBased on Anansi the spider folktales from West Africa and the Caribbean. Anansi's children want to play with their friends, but the parents do no...    1
• Author(s): Fyodor Dostoyevsky • Publisher: Penguin • Publisher Imprint: Penguin • Subject: Creative Writing, Fiction • BISAC: ClassicsFyodor Dostoyevsky's powerful meditation on faith, meaning and morality, The Brothers Karamazov is translated ...    1
• Author(s): Alexandre Dumas Pere • Publisher: Penguin Books • Publisher Imprint: Penguin Books • BISAC: ClassicsAlexandre Dumas's epic tale of suffering and retribution, inspired by a real-life case of wrongful imprisonment--nominated as one of ...    1
• Author(s): Bibek Debroy • Publisher: India Penguin Classics • Publisher Imprint: India Penguin Classics • BISAC: Hinduism - HistoryLORD VISHNU AND THE CREATION The Vishnu Purana is part of a series of eighteen sacred Hindu texts known collectiv...    1
• Author(s): PhD Kevin Hall • Publisher: Headline Publishing Group • Publisher Imprint: Headline Publishing Group • BISAC: Diet & Nutrition - Nutrition                                                                                                      1
Name: count, Length: 869, dtype: int64

In [867]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   945 non-null    int64
 1   title                  945 non-null    str
 2   writer                 945 non-null    str
 3   format                 929 non-null    str
 4   actual_price           945 non-null    str
 5   price_before_discount  944 non-null    str
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
dtypes: float64(2), int64(1), str(6)
memory usage: 66.6 KB

In [868]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...

In [869]:
df["stars"].value_counts()

stars
5.0    11
3.5     1
3.0     1
2.0     1
Name: count, dtype: int64

In [870]:
s=df["bullet_9"].str.split("•")

In [871]:
s

0      [,  Author(s): Clear | James ,  Publ...
1      [,  Author(s): Hector Garcia ,  Publ...
2      [,  Author(s): Ichiro Kishimi ,  Pub...
3      [,  Author(s): Chetan Bhagat ,  Publ...
4      [,  Author(s): Brianna Wiest ,  Publ...
                        ...
940    [,  Author(s): Ladybird ,  Publisher...
941    [,  Author(s): Fyodor Dostoyevsky , ...
942    [,  Author(s): Alexandre Dumas Pere ...
943    [,  Author(s): Bibek Debroy ,  Publi...
944    [,  Author(s): PhD Kevin Hall ,  Pub...
Name: bullet_9, Length: 945, dtype: object

In [872]:
df["author"]=s.str[1]

In [873]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9                       author
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...    Author(s): Clear | James
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...    Author(s): Hector Garcia
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...   Author(s): Ichiro Kishimi
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...    Author(s): Chetan Bhagat
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...    Author(s): Brianna Wiest

In [874]:
df["publisher"]=s.str[2]

In [875]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9                       author                                publisher
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...    Author(s): Clear | James                       Publisher: Penguin
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...    Author(s): Hector Garcia                       Publisher: Penguin
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...   Author(s): Ichiro Kishimi                Publisher: GROVE ATLANTIC
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...    Author(s): Chetan Bhagat    Publisher: HarperCollins Publishers...
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...    Author(s): Brianna Wiest             Publisher: Manjul Publishing

In [876]:
df["author"].value_counts()

author
Author(s): Jeff Kinney              19
Author(s): Rick Riordan             16
Author(s): Sudha Murty              12
Author(s): J. K. Rowling            11
Author(s): Freida Mcfadden          10
                                    ..
Author(s): Sidney Sheldon            1
Author(s): Marco Iansiti             1
Author(s): Ravi Mantrii              1
Author(s): Alexandre Dumas Pere      1
Author(s): PhD Kevin Hall            1
Name: count, Length: 659, dtype: int64

In [877]:
df["publisher"].value_counts()

publisher
Publisher: Penguin Books Ltd                      71
Publisher: HarperCollins Publishers               63
Publisher: Penguin Random House Children's UK     59
Publisher: PRH INDIA LOCAL PRINT                  37
Publisher: HarperCollins India                    33
                                                  ..
Publisher: Everyman                                1
Publisher: ONEWorld Publications                   1
Publisher: DK Publishing (Dorling Kindersley)      1
Publisher: Harvard Business School Press           1
Publisher: Ladybird                                1
Name: count, Length: 193, dtype: int64

In [878]:
df[df["publisher"].isna()]

     page              title         writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9 author publisher
693    12          The Guide  Louis L'Amour  Paperback         ₹245                   NaN               NaN    NaN                                      NaN    NaN       NaN
866    15  The Infinite Game    Simon Sinek  Paperback         ₹650                  ₹999              35.0    NaN  NEW YORK TIMES BESTSELLERThe New Yor...    NaN       NaN

In [879]:
df["author"]=df["author"].str.replace("Author(s): ", "")

In [880]:
df.head()

   page                                    title          writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9            author                                publisher
0     1               Atomic Habits (Lead Title)    Clear, James  Paperback         ₹650                  ₹999              35.0    3.5  • Author(s): Clear | James • Publish...    Clear | James                       Publisher: Penguin
1     1                                   Ikigai   Hector Garcia  Hardcover         ₹390                  ₹599              35.0    NaN  • Author(s): Hector Garcia • Publish...    Hector Garcia                       Publisher: Penguin
2     1  The Courage To Be Disliked How To Fr...  Ichiro Kishimi  Hardcover         ₹390                  ₹599              35.0    5.0  • Author(s): Ichiro Kishimi • Publis...   Ichiro Kishimi                Publisher: GROVE ATLANTIC
3     1        12 Years: My Messed-up Love Story   Chetan Bhagat  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Chetan Bhagat • Publish...    Chetan Bhagat    Publisher: HarperCollins Publishers...
4     1  The Mountain Is You: Transforming Se...   Brianna Wiest  Paperback         ₹260                  ₹399              35.0    NaN  • Author(s): Brianna Wiest • Publish...    Brianna Wiest             Publisher: Manjul Publishing

In [881]:
df["publisher"]=df["publisher"].str.replace("Publisher: ", "")

In [882]:
df.head(20)

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing
5,1,The Art of Spending Money: Simple Ch...,Morgan Housel,Paperback,₹290,₹499,42.0,5.0,• Author(s): Morgan Housel • Publish...,Morgan Housel,Pan Macmillan
6,1,Mother Mary Comes To Me,Arundhati Roy,Hardcover,₹585,₹899,35.0,NaN,• Author(s): Arundhati Roy• Publishe...,Arundhati Roy,PRH INDIA LOCAL PRINT
7,1,Truth without Apology: A Guide for T...,Acharya Prashant,Paperback,₹260,₹399,35.0,NaN,• Author(s): Acharya Prashant • Publ...,Acharya Prashant,HarperCollins Publishers India
8,1,Grandma's Bag of Stories,Sudha Murthy,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murthy • Publishe...,Sudha Murthy,India Puffin
9,1,Days at the Morisaki Bookshop,Satoshi Yagisawa,Paperback,₹260,₹399,35.0,5.0,• Author(s): Satoshi Yagisawa • Publ...,Satoshi Yagisawa,Bonnier Books Ltd
10,1,Deep Work: Rules For Focused Success...,"Newport, Cal",Paperback,₹260,₹399,35.0,NaN,"• Author(s): Newport, Cal • Publishe...","Newport, Cal","Little, Brown Book Group"
11,1,Can We Be Strangers Again?: A Nation...,Shrijeet Shandilya,Paperback,₹195,₹299,35.0,NaN,• Author(s): Shrijeet Shandilya • Pu...,Shrijeet Shandilya,Ebury Press
12,1,The Secret of Secrets: (Robert Langd...,Dan Brown,Hardcover,₹975,"₹1,499",35.0,NaN,• Author(s): Dan Brown • Publisher: ...,Dan Brown,Transworld Publishers Ltd
13,1,Magic of the Lost Temple,Sudha Murty,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murty • Publisher...,Sudha Murty,India Puffin
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,Publisher: Penguin,Publisher Imprint: Penguin Random H...
15,1,World’S Greatest Books For Personal ...,"Dale Carnegie, Napoleon Hill",Paperback,₹390,₹599,35.0,NaN,• Author(s): Dale Carnegie | Napoleo...,Dale Carnegie | Napoleon Hill,Fingerprint
16,1,The Housemaid: An Addictive Psycholo...,Freida Mcfadden,Paperback,₹358,₹550,35.0,NaN,• Author(s): Freida Mcfadden • Publi...,Freida Mcfadden,Penguin Select Print
17,1,101 Tales: The Great Panchatantra Co...,Wonder House Books,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Wonder House Books • Pu...,Wonder House Books,Wonder House Books
18,1,Man's Search For Meaning,Viktor E. Frankl,Paperback,₹293,₹450,35.0,NaN,• Author(s): Viktor E. Frankl • Publ...,Viktor E. Frankl,Random House
19,1,Bacchon KI Doctor's Desi Parenting B...,Madhavi Bharadwaj,Paperback,₹260,₹399,35.0,NaN,• Author(s): Madhavi Bharadwaj • Pub...,Madhavi Bharadwaj,PRH India

In [883]:
df[df["author"].str.contains("Publisher:", na=False, case=False)]

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,Publisher: Penguin,Publisher Imprint: Penguin Random H...
267,5,Tom Gates #01: The Brilliant World o...,Paperback,Paperback,₹380,₹399,5.0,NaN,• Publisher: MIXIG • Publisher Impri...,Publisher: MIXIG,Publisher Imprint: MIXIG
595,10,The Three-Body Problem Boxset,Misc,NaN,"₹1,235","₹1,899",35.0,NaN,• Publisher: Bloomsbury Publishing P...,Publisher: Bloomsbury Publishing PLC,Publisher Imprint: Bloomsbury Publi...
633,11,Intermezzo,Paperback,Paperback,₹455,₹699,35.0,NaN,• Publisher: Faber & Faber • Publish...,Publisher: Faber & Faber,Publisher Imprint: Faber & Faber
802,14,"Many Ramayanas, Many Lessons",Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: HarperCollins Publisher...,Publisher: HarperCollins Publishers...,Publisher Imprint: HarperCollins Pu...

In [884]:
df[df["author"].str.contains("Publisher:", na=False)]

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,Publisher: Penguin,Publisher Imprint: Penguin Random H...
267,5,Tom Gates #01: The Brilliant World o...,Paperback,Paperback,₹380,₹399,5.0,NaN,• Publisher: MIXIG • Publisher Impri...,Publisher: MIXIG,Publisher Imprint: MIXIG
595,10,The Three-Body Problem Boxset,Misc,NaN,"₹1,235","₹1,899",35.0,NaN,• Publisher: Bloomsbury Publishing P...,Publisher: Bloomsbury Publishing PLC,Publisher Imprint: Bloomsbury Publi...
633,11,Intermezzo,Paperback,Paperback,₹455,₹699,35.0,NaN,• Publisher: Faber & Faber • Publish...,Publisher: Faber & Faber,Publisher Imprint: Faber & Faber
802,14,"Many Ramayanas, Many Lessons",Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: HarperCollins Publisher...,Publisher: HarperCollins Publishers...,Publisher Imprint: HarperCollins Pu...

In [885]:
df.head(20)

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing
5,1,The Art of Spending Money: Simple Ch...,Morgan Housel,Paperback,₹290,₹499,42.0,5.0,• Author(s): Morgan Housel • Publish...,Morgan Housel,Pan Macmillan
6,1,Mother Mary Comes To Me,Arundhati Roy,Hardcover,₹585,₹899,35.0,NaN,• Author(s): Arundhati Roy• Publishe...,Arundhati Roy,PRH INDIA LOCAL PRINT
7,1,Truth without Apology: A Guide for T...,Acharya Prashant,Paperback,₹260,₹399,35.0,NaN,• Author(s): Acharya Prashant • Publ...,Acharya Prashant,HarperCollins Publishers India
8,1,Grandma's Bag of Stories,Sudha Murthy,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murthy • Publishe...,Sudha Murthy,India Puffin
9,1,Days at the Morisaki Bookshop,Satoshi Yagisawa,Paperback,₹260,₹399,35.0,5.0,• Author(s): Satoshi Yagisawa • Publ...,Satoshi Yagisawa,Bonnier Books Ltd
10,1,Deep Work: Rules For Focused Success...,"Newport, Cal",Paperback,₹260,₹399,35.0,NaN,"• Author(s): Newport, Cal • Publishe...","Newport, Cal","Little, Brown Book Group"
11,1,Can We Be Strangers Again?: A Nation...,Shrijeet Shandilya,Paperback,₹195,₹299,35.0,NaN,• Author(s): Shrijeet Shandilya • Pu...,Shrijeet Shandilya,Ebury Press
12,1,The Secret of Secrets: (Robert Langd...,Dan Brown,Hardcover,₹975,"₹1,499",35.0,NaN,• Author(s): Dan Brown • Publisher: ...,Dan Brown,Transworld Publishers Ltd
13,1,Magic of the Lost Temple,Sudha Murty,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murty • Publisher...,Sudha Murty,India Puffin
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,Publisher: Penguin,Publisher Imprint: Penguin Random H...
15,1,World’S Greatest Books For Personal ...,"Dale Carnegie, Napoleon Hill",Paperback,₹390,₹599,35.0,NaN,• Author(s): Dale Carnegie | Napoleo...,Dale Carnegie | Napoleon Hill,Fingerprint
16,1,The Housemaid: An Addictive Psycholo...,Freida Mcfadden,Paperback,₹358,₹550,35.0,NaN,• Author(s): Freida Mcfadden • Publi...,Freida Mcfadden,Penguin Select Print
17,1,101 Tales: The Great Panchatantra Co...,Wonder House Books,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Wonder House Books • Pu...,Wonder House Books,Wonder House Books
18,1,Man's Search For Meaning,Viktor E. Frankl,Paperback,₹293,₹450,35.0,NaN,• Author(s): Viktor E. Frankl • Publ...,Viktor E. Frankl,Random House
19,1,Bacchon KI Doctor's Desi Parenting B...,Madhavi Bharadwaj,Paperback,₹260,₹399,35.0,NaN,• Author(s): Madhavi Bharadwaj • Pub...,Madhavi Bharadwaj,PRH India

In [886]:
df["publisher_imprint"]=s.str[3]

In [887]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin,Publisher Imprint: Penguin Random H...
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin,Publisher Imprint: Penguin Random H...
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC,Publisher Imprint: Allen & Unwin
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India,Publisher Imprint: HarperCollins Pu...
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing,Publisher Imprint: Amaryllis

In [888]:
df["publisher_imprint"]=df["publisher_imprint"].str.replace("Publisher Imprint: ", "")

In [889]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin,Penguin Random House
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin,Penguin Random House
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC,Allen & Unwin
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India,HarperCollins Publishers India
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing,Amaryllis

In [890]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   945 non-null    int64
 1   title                  945 non-null    str
 2   writer                 945 non-null    str
 3   format                 929 non-null    str
 4   actual_price           945 non-null    str
 5   price_before_discount  944 non-null    str
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
 9   author                 943 non-null    object
 10  publisher              943 non-null    object
 11  publisher_imprint      940 non-null    object
dtypes: float64(2), int64(1), object(3), str(6)
memory usage: 88.7+ KB

In [891]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin,Penguin Random House
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin,Penguin Random House
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC,Allen & Unwin
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India,HarperCollins Publishers India
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing,Amaryllis

In [892]:
GLUE = re.compile(r"(?<=[a-z]{2})(?=[A-Z])")  # 2+ lowercase then capital, no space
PROTECTED = re.compile("WordPress|JavaScript|TypeScript|YouTube|PowerPoint|LinkedIn|PlayStation")

def _split(text):
    if not text:
        return np.nan, np.nan
    spans = [m.span() for m in PROTECTED.finditer(text)]
    m = next((m for m in GLUE.finditer(text) if not any(a < m.start() < b for a, b in spans)), None)
    val, desc = (text[:m.start()], text[m.start():]) if m else (text, "")
    return val.strip() or np.nan, desc.strip() or np.nan

def split_bullet_column(df, col="bullet_9"):
    def parse(s):
        f = {k.lower(): v.strip() for k, v in re.findall(r"•\s*([^:•]+?)\s*:\s*([^•]*)", s)} if isinstance(s, str) else {}
        return [*_split(f.get("subject")), *_split(f.get("bisac"))]
    df[["subject", "subject_description", "bisac", "bisac_description"]] = [parse(s) for s in df[col]]
    return df

In [893]:
df = split_bullet_column(df, col="bullet_9")
df[["subject", "subject_description", "bisac", "bisac_description"]].head()

         subject subject_description                      bisac                        bisac_description
0  General Books                 NaN                        NaN                                      NaN
1  General Books                 NaN                        NaN                                      NaN
2            NaN                 NaN  Personal Growth - Success  Ichiro Kishimi lives in Kyoto. He wr...
3            NaN                 NaN                    General  From India's top-selling writer Chet...
4            NaN                 NaN       Body Mind And Spirit  This is a book about self-sabotage. ...

In [894]:
df.head(35)

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin,Penguin Random House,General Books,NaN,NaN,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin,Penguin Random House,General Books,NaN,NaN,NaN
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC,Allen & Unwin,NaN,NaN,Personal Growth - Success,Ichiro Kishimi lives in Kyoto. He wr...
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,General,From India's top-selling writer Chet...
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing,Amaryllis,NaN,NaN,Body Mind And Spirit,This is a book about self-sabotage. ...
5,1,The Art of Spending Money: Simple Ch...,Morgan Housel,Paperback,₹290,₹499,42.0,5.0,• Author(s): Morgan Housel • Publish...,Morgan Housel,Pan Macmillan,Pan Macmillan,NaN,NaN,Finance - Wealth Management,A third book from the International ...
6,1,Mother Mary Comes To Me,Arundhati Roy,Hardcover,₹585,₹899,35.0,NaN,• Author(s): Arundhati Roy• Publishe...,Arundhati Roy,PRH INDIA LOCAL PRINT,Penguin Hamish Hamilton,NaN,NaN,Literary Figures,Arundhati Roy’s first work of memoir...
7,1,Truth without Apology: A Guide for T...,Acharya Prashant,Paperback,₹260,₹399,35.0,NaN,• Author(s): Acharya Prashant • Publ...,Acharya Prashant,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,General,In a world where vagueness is mistak...
8,1,Grandma's Bag of Stories,Sudha Murthy,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murthy • Publishe...,Sudha Murthy,India Puffin,India Puffin,NaN,NaN,Short Stories,"Who can resist a good story, especia..."
9,1,Days at the Morisaki Bookshop,Satoshi Yagisawa,Paperback,₹260,₹399,35.0,5.0,• Author(s): Satoshi Yagisawa • Publ...,Satoshi Yagisawa,Bonnier Books Ltd,Bonnier Books Ltd,NaN,NaN,NaN,NaN
10,1,Deep Work: Rules For Focused Success...,"Newport, Cal",Paperback,₹260,₹399,35.0,NaN,"• Author(s): Newport, Cal • Publishe...","Newport, Cal","Little, Brown Book Group",Piatkus,NaN,NaN,NaN,NaN
11,1,Can We Be Strangers Again?: A Nation...,Shrijeet Shandilya,Paperback,₹195,₹299,35.0,NaN,• Author(s): Shrijeet Shandilya • Pu...,Shrijeet Shandilya,Ebury Press,Ebury Press,NaN,NaN,Romance - General,In the electric haze of college life...
12,1,The Secret of Secrets: (Robert Langd...,Dan Brown,Hardcover,₹975,"₹1,499",35.0,NaN,• Author(s): Dan Brown • Publisher: ...,Dan Brown,Transworld Publishers Ltd,Transworld Publishers Ltd,NaN,NaN,Thrillers - Espionage,Dan Brown is the bestselling author ...
13,1,Magic of the Lost Temple,Sudha Murty,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murty • Publisher...,Sudha Murty,India Puffin,India Puffin,NaN,NaN,Action & Adventure - General,NaN
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,Publisher: Penguin,Publisher Imprint: Penguin Random H...,Subject: General Books,General Books,NaN,Personal Finance - General,April of 2022 marks a 25-year milest...
15,1,World’S Greatest Books For Personal ...,"Dale Carnegie, Napoleon Hill",Paperback,₹390,₹599,35.0,NaN,• Author(s): Dale Carnegie | Napoleo...,Dale Carnegie | Napoleon Hill,Fingerprint,Fingerprint,General Books,NaN,NaN,NaN
16,1,The Housemaid: An Addictive Psycholo...,Freida Mcfadden,Paperback,₹358,₹550,35.0,NaN,• Author(s): Freida Mcfadden • Publi...,Freida Mcfadden,Penguin Select Print,"Penguin Select Publishing""Multi-Mil...",NaN,NaN,NaN,NaN
17,1,101 Tales: The Great Panchatantra Co...,Wonder House Books,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Wonder House Books • Pu...,Wonder House Books,Wonder House Books,Wonder House Books,NaN,NaN,Comics & Graphic Novels - Fairy Tale...,NaN
18,1,Man's Search For Meaning,Viktor E. Frankl,Paperback,₹293,₹450,35.0,NaN,• Author(s): Viktor E. Frankl • Publ...,Viktor E. Frankl,Random House,Random Hou,"Medical, Nursing and Health Sciences",NaN,NaN,NaN
19,1,Bacchon KI Doctor's Desi Parenting B...,Madhavi Bharadwaj,Paperback,₹260,₹399,35.0,NaN,• Author(s): Madhavi Bharadwaj • Pub...,Madhavi Bharadwaj,PRH India,Penguin Ebury Press,NaN,NaN,Parenting - Motherhood,"Welcome to the wild, messy, wonderfu..."
20,1,The Outsider,Vir Das,Hardcover,₹455,₹699,35.0,NaN,• Author(s): Vir Das • Publisher: Ha...,Vir Das,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,Entertainment & Performing Arts,Comedian and actor Vir Das is belove...
21,1,The Very Hungry Caterpillar,Eric Carle,Board Book,₹293,₹450,35.0,NaN,• Author(s): Eric Carle • Publisher:...,Eric Carle,"Penguin Books, Limited (UK)","Penguin Books, Limited (UK)",NaN,NaN,"Animals - Butterflies, Moths & Cater...",Eric Carle's The Very Hungry Caterpi...
22,1,"Too Good to Be True : A smart, funny...",Prajakta Koli,Paperback,₹260,₹399,35.0,NaN,• Author(s): Prajakta Koli • Publish...,Prajakta Koli,Harper Fiction India,Harper Fiction India,NaN,NaN,Romance - Contemporary,Winner of the Amazon India Popular C...
23,1,Tuesdays With Morrie (Export) (A For...,"Albom, Mitch",Paperback,₹195,₹299,35.0,NaN,"• Author(s): Albom, Mitch • Publishe...","Albom, Mitch","Little, Brown Book Group","Sphere* Subtitled 'An old man, a yo...",NaN,NaN,NaN,NaN
24,1,The Hard Thing about Hard Things: Bu...,Ben Horowitz,Hardcover,₹585,₹899,35.0,NaN,• Author(s): Ben Horowitz • Publishe...,Ben Horowitz,HarperBusiness,HarperBusiness,NaN,NaN,Management - General,From the Back CoverA lot of people t...
25,1,The 48 Laws Of Power,"Greene, Robert",Paperback,₹650,₹999,35.0,5.0,"• Author(s): Greene, Robert • Publis...","Greene, Robert",Profile Books Ltd,"Profile BooksDrawn from 3,000 years...",NaN,NaN,NaN,NaN
26,1,A Little Life,Hanya Yanagihara,Paperback,₹406,₹699,42.0,NaN,• Author(s): Hanya Yanagihara • Publ...,Hanya Yanagihara,Pan Books Ltd,Pan Books Ltd'I'm not exaggerating ...,NaN,NaN,NaN,NaN
27,1,The Chola Tigers: Avengers of Somnath,Amish,Paperback,₹325,₹499,35.0,NaN,• Author(s): Amish • Publisher: Harp...,Amish,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,Historical - Ancient,From the grandeur of the Chola Empir...
28,1,The Pallace Of Illusions (10 Anniver...,Chitra Divakaruni,Paperback,₹290,₹499,42.0,NaN,• Author(s): Chitra Divakaruni • Pub...,Chitra Divakaruni,Pan Books Ltd,"Pan Books Ltd""Be taken back to a ti...",NaN,NaN,NaN,NaN
29,1,Mindset (Revised And Updated),"Dweck, Carol",Paperback,₹260,₹399,35.0,NaN,"• Author(s): Dweck, Carol • Publishe...","Dweck, Carol","Little, Brown Book Group",RobinsonWorld-renowned Stanford Uni...,NaN,NaN,NaN,NaN
30,1,Harry Potter and the Philosopher's S...,J. K. Rowling,Paperback,₹390,₹599,35.0,NaN,• Author(s): J. K. Rowling • Publish...,J. K. Rowling,Bloomsbury,Bloomsbury Children's Books,"Creative Writing, Fiction",Harry Potter lives in a cupboard und...,NaN,NaN
31,1,The Let Them Theory,Robbins Mel,Hardcover,₹520,₹799,35.0,NaN,• Author(s): Robbins Mel • Publisher...,Robbins Mel,Hay House,HayHouse,"Creative Writing, Fiction",New York Time Bestselling Author. Mi...,NaN,NaN
32,1,Manifest,Roxie Nafousi,Hardcover,₹455,₹699,35.0,NaN,• Author(s): Roxie Nafousi • Publish...,Roxie Nafousi,Penguin Books Ltd,Penguin Books Ltd,NaN,NaN,NaN,NaN
33,1,Diary of a Wimpy Kid (Book 1),Jeff Kinney,Paperback,₹260,₹399,35.0,NaN,• Author(s): Jeff Kinney • Publisher...,Jeff Kinney,Penguin Random House Children's UK,Penguin Random House Children's UKG...,NaN,NaN,NaN,NaN
34,1,Mahagatha: 100 Tales from the Puranas,Satyarth Nayak,Paperback,₹390,₹599,35.0,NaN,• Author(s): Satyarth Nayak • Publis...,Satyarth Nayak,HarperCollins India,HarperCollins India,NaN,NaN,Folklore & Mythology,The Puranas of Hinduism are a univer...

In [895]:
df[df["author"].str.contains("Publisher:", na=False)]

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,Publisher: Penguin,Publisher Imprint: Penguin Random H...,Subject: General Books,General Books,NaN,Personal Finance - General,April of 2022 marks a 25-year milest...
267,5,Tom Gates #01: The Brilliant World o...,Paperback,Paperback,₹380,₹399,5.0,NaN,• Publisher: MIXIG • Publisher Impri...,Publisher: MIXIG,Publisher Imprint: MIXIG,Subject: General BooksThe top-selli...,General Books,The top-selling U.K. Series for midd...,NaN,NaN
595,10,The Three-Body Problem Boxset,Misc,NaN,"₹1,235","₹1,899",35.0,NaN,• Publisher: Bloomsbury Publishing P...,Publisher: Bloomsbury Publishing PLC,Publisher Imprint: Bloomsbury Publi...,NaN,NaN,NaN,NaN,NaN
633,11,Intermezzo,Paperback,Paperback,₹455,₹699,35.0,NaN,• Publisher: Faber & Faber • Publish...,Publisher: Faber & Faber,Publisher Imprint: Faber & Faber,NaN,NaN,NaN,NaN,NaN
802,14,"Many Ramayanas, Many Lessons",Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: HarperCollins Publisher...,Publisher: HarperCollins Publishers...,Publisher Imprint: HarperCollins Pu...,NaN,NaN,NaN,NaN,NaN

In [896]:
m = df["author"].str.contains("Publisher:", na=False)

# Publisher column ka data publisher_imprint mein shift karo
df.loc[m, "publisher_imprint"] = df.loc[m, "publisher"]

# Author column ka data publisher mein shift karo
df.loc[m, "publisher"] = df.loc[m, "author"]

# Author column ko empty karo
df.loc[m, "author"] = None

In [897]:
df[df["author"].str.contains("Publisher:", na=False)]

Empty DataFrame
Columns: [page, title, writer, format, actual_price, price_before_discount, discount_percent, stars, bullet_9, author, publisher, publisher_imprint, subject, subject_description, bisac, bisac_description]
Index: []

In [898]:
df["publisher"]=df["publisher"].str.replace("Publisher: ", "")

In [899]:
df["publisher_imprint"]=df["publisher_imprint"].str.replace("Publisher Imprint: ", "")

In [900]:
df.head(20)

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin,Penguin Random House,General Books,NaN,NaN,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin,Penguin Random House,General Books,NaN,NaN,NaN
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC,Allen & Unwin,NaN,NaN,Personal Growth - Success,Ichiro Kishimi lives in Kyoto. He wr...
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,General,From India's top-selling writer Chet...
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing,Amaryllis,NaN,NaN,Body Mind And Spirit,This is a book about self-sabotage. ...
5,1,The Art of Spending Money: Simple Ch...,Morgan Housel,Paperback,₹290,₹499,42.0,5.0,• Author(s): Morgan Housel • Publish...,Morgan Housel,Pan Macmillan,Pan Macmillan,NaN,NaN,Finance - Wealth Management,A third book from the International ...
6,1,Mother Mary Comes To Me,Arundhati Roy,Hardcover,₹585,₹899,35.0,NaN,• Author(s): Arundhati Roy• Publishe...,Arundhati Roy,PRH INDIA LOCAL PRINT,Penguin Hamish Hamilton,NaN,NaN,Literary Figures,Arundhati Roy’s first work of memoir...
7,1,Truth without Apology: A Guide for T...,Acharya Prashant,Paperback,₹260,₹399,35.0,NaN,• Author(s): Acharya Prashant • Publ...,Acharya Prashant,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,General,In a world where vagueness is mistak...
8,1,Grandma's Bag of Stories,Sudha Murthy,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murthy • Publishe...,Sudha Murthy,India Puffin,India Puffin,NaN,NaN,Short Stories,"Who can resist a good story, especia..."
9,1,Days at the Morisaki Bookshop,Satoshi Yagisawa,Paperback,₹260,₹399,35.0,5.0,• Author(s): Satoshi Yagisawa • Publ...,Satoshi Yagisawa,Bonnier Books Ltd,Bonnier Books Ltd,NaN,NaN,NaN,NaN
10,1,Deep Work: Rules For Focused Success...,"Newport, Cal",Paperback,₹260,₹399,35.0,NaN,"• Author(s): Newport, Cal • Publishe...","Newport, Cal","Little, Brown Book Group",Piatkus,NaN,NaN,NaN,NaN
11,1,Can We Be Strangers Again?: A Nation...,Shrijeet Shandilya,Paperback,₹195,₹299,35.0,NaN,• Author(s): Shrijeet Shandilya • Pu...,Shrijeet Shandilya,Ebury Press,Ebury Press,NaN,NaN,Romance - General,In the electric haze of college life...
12,1,The Secret of Secrets: (Robert Langd...,Dan Brown,Hardcover,₹975,"₹1,499",35.0,NaN,• Author(s): Dan Brown • Publisher: ...,Dan Brown,Transworld Publishers Ltd,Transworld Publishers Ltd,NaN,NaN,Thrillers - Espionage,Dan Brown is the bestselling author ...
13,1,Magic of the Lost Temple,Sudha Murty,Paperback,₹179,₹275,35.0,NaN,• Author(s): Sudha Murty • Publisher...,Sudha Murty,India Puffin,India Puffin,NaN,NaN,Action & Adventure - General,NaN
14,1,Rich Dad Poor Dad: What the Rich Tea...,Paperback,Paperback,₹390,₹599,35.0,NaN,• Publisher: Penguin • Publisher Imp...,None,Penguin,Penguin Random House,General Books,NaN,Personal Finance - General,April of 2022 marks a 25-year milest...
15,1,World’S Greatest Books For Personal ...,"Dale Carnegie, Napoleon Hill",Paperback,₹390,₹599,35.0,NaN,• Author(s): Dale Carnegie | Napoleo...,Dale Carnegie | Napoleon Hill,Fingerprint,Fingerprint,General Books,NaN,NaN,NaN
16,1,The Housemaid: An Addictive Psycholo...,Freida Mcfadden,Paperback,₹358,₹550,35.0,NaN,• Author(s): Freida Mcfadden • Publi...,Freida Mcfadden,Penguin Select Print,"Penguin Select Publishing""Multi-Mil...",NaN,NaN,NaN,NaN
17,1,101 Tales: The Great Panchatantra Co...,Wonder House Books,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Wonder House Books • Pu...,Wonder House Books,Wonder House Books,Wonder House Books,NaN,NaN,Comics & Graphic Novels - Fairy Tale...,NaN
18,1,Man's Search For Meaning,Viktor E. Frankl,Paperback,₹293,₹450,35.0,NaN,• Author(s): Viktor E. Frankl • Publ...,Viktor E. Frankl,Random House,Random Hou,"Medical, Nursing and Health Sciences",NaN,NaN,NaN
19,1,Bacchon KI Doctor's Desi Parenting B...,Madhavi Bharadwaj,Paperback,₹260,₹399,35.0,NaN,• Author(s): Madhavi Bharadwaj • Pub...,Madhavi Bharadwaj,PRH India,Penguin Ebury Press,NaN,NaN,Parenting - Motherhood,"Welcome to the wild, messy, wonderfu..."

In [901]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   945 non-null    int64
 1   title                  945 non-null    str
 2   writer                 945 non-null    str
 3   format                 929 non-null    str
 4   actual_price           945 non-null    str
 5   price_before_discount  944 non-null    str
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
 9   author                 938 non-null    object
 10  publisher              943 non-null    object
 11  publisher_imprint      943 non-null    object
 12  subject                91 non-null     str
 13  subject_description    27 non-null     str
 14  bisac                  408 non-null    str
 15  bisac_description      258 non-null    str
dtypes: float64(2), int64(1), object(3), str(10)
memory usage: 118.3+ KB

In [902]:
df.drop(df[df["price_before_discount"].isna()].index, inplace=True)

In [903]:
df.info()

<class 'pandas.DataFrame'>
Index: 944 entries, 0 to 944
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   944 non-null    int64
 1   title                  944 non-null    str
 2   writer                 944 non-null    str
 3   format                 928 non-null    str
 4   actual_price           944 non-null    str
 5   price_before_discount  944 non-null    str
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
 9   author                 938 non-null    object
 10  publisher              943 non-null    object
 11  publisher_imprint      943 non-null    object
 12  subject                91 non-null     str
 13  subject_description    27 non-null     str
 14  bisac                  408 non-null    str
 15  bisac_description      258 non-null    str
dtypes: float64(2), int64(1), object(3), str(10)
memory usage: 125.4+ KB

In [904]:
df[df["publisher"].isna()]

     page              title       writer     format actual_price price_before_discount  discount_percent  stars                                 bullet_9 author publisher publisher_imprint subject subject_description bisac bisac_description
866    15  The Infinite Game  Simon Sinek  Paperback         ₹650                  ₹999              35.0    NaN  NEW YORK TIMES BESTSELLERThe New Yor...    NaN       NaN               NaN     NaN                 NaN   NaN               NaN

In [905]:
df["actual_price"]=df["actual_price"].str.strip().str.replace("₹","").str.replace(",","")

In [906]:
#df["actual_price"] = df["actual_price"].astype(int)

In [907]:
df[df["actual_price"].str.contains("$", regex=False, na=False)]

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
844,15,In Service of the Republic: The Art ...,Vijay Kelkar,Paperback,$3,₹599,35.0,NaN,• Author(s): Vijay Kelkar • Publishe...,Vijay Kelkar,India Penguin,India Penguin,NaN,NaN,Public Policy - Economic Policy,"As a $3-trillion economy, India is o..."

In [908]:
df.loc[844, "actual_price"] = str(round(3 * 95.18))

In [909]:
df["actual_price"] = df["actual_price"].astype(int)

In [910]:
df["price_before_discount"]=df["price_before_discount"].str.strip().str.replace("₹","").str.replace(",","")

In [911]:
df["price_before_discount"] = df["price_before_discount"].astype(int)

In [912]:
df.head(87)

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,650,999,35.0,3.5,• Author(s): Clear | James • Publish...,Clear | James,Penguin,Penguin Random House,General Books,NaN,NaN,NaN
1,1,Ikigai,Hector Garcia,Hardcover,390,599,35.0,NaN,• Author(s): Hector Garcia • Publish...,Hector Garcia,Penguin,Penguin Random House,General Books,NaN,NaN,NaN
2,1,The Courage To Be Disliked How To Fr...,Ichiro Kishimi,Hardcover,390,599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,Ichiro Kishimi,GROVE ATLANTIC,Allen & Unwin,NaN,NaN,Personal Growth - Success,Ichiro Kishimi lives in Kyoto. He wr...
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,260,399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,Chetan Bhagat,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,General,From India's top-selling writer Chet...
4,1,The Mountain Is You: Transforming Se...,Brianna Wiest,Paperback,260,399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,Brianna Wiest,Manjul Publishing,Amaryllis,NaN,NaN,Body Mind And Spirit,This is a book about self-sabotage. ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2,Good Material,Dolly Alderton,Paperback,455,699,35.0,NaN,• Author(s): Dolly Alderton • Publis...,Dolly Alderton,Penguin Books Ltd,Penguin Books Ltd,NaN,NaN,NaN,NaN
83,2,Diary of a Wimpy Kid: Hot Mess (Book...,Jeff Kinney,Hardcover,1352,1949,31.0,NaN,• Author(s): Jeff Kinney • Publisher...,Jeff Kinney,Penguin Random House Children's UK,Penguin Random House Children's UK,NaN,NaN,NaN,NaN
84,2,Wings Of Valour: True Stories of the...,Swapnil Pandey,Paperback,260,399,35.0,NaN,• Author(s): Swapnil Pandey • Publis...,Swapnil Pandey,HarperCollins Publishers India,HarperCollins Publishers India,NaN,NaN,Aviation & Nautical,After travelling across Indian airba...
85,2,My First Sudha Murty Collection,Sudha Murty,Hardcover,715,1099,35.0,NaN,• Author(s): Sudha Murty • Publisher...,Sudha Murty,PRH INDIA LOCAL PRINT,Puffin,NaN,NaN,Readers - Beginner,Puffin Chapter books is a series of ...
86,2,Harry Potter and the Chamber of Secrets,J. K. Rowling,Paperback,390,599,35.0,NaN,• Author(s): J. K. Rowling • Publish...,J. K. Rowling,Bloomsbury Publishing PLC,Bloomsbury Publishing PLC,NaN,NaN,NaN,NaN

In [913]:
df.info()

<class 'pandas.DataFrame'>
Index: 944 entries, 0 to 944
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   944 non-null    int64
 1   title                  944 non-null    str
 2   writer                 944 non-null    str
 3   format                 928 non-null    str
 4   actual_price           944 non-null    int64
 5   price_before_discount  944 non-null    int64
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
 9   author                 938 non-null    object
 10  publisher              943 non-null    object
 11  publisher_imprint      943 non-null    object
 12  subject                91 non-null     str
 13  subject_description    27 non-null     str
 14  bisac                  408 non-null    str
 15  bisac_description      258 non-null    str
dtypes: float64(2), int64(3), object(3), str(8)
memory usage: 157.7+ KB

In [914]:
cols = [
    "title",
    "writer",
    "format",
    "author",
    "publisher",
    "publisher_imprint",
    "subject",
    "subject_description",
    "bisac",
    "bisac_description"
]

df[cols] = df[cols].map(
    lambda x: x.strip().lower() if isinstance(x, str) else x
)

In [915]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,author,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
0,1,atomic habits (lead title),"clear, james",paperback,650,999,35.0,3.5,• Author(s): Clear | James • Publish...,clear | james,penguin,penguin random house,general books,NaN,NaN,NaN
1,1,ikigai,hector garcia,hardcover,390,599,35.0,NaN,• Author(s): Hector Garcia • Publish...,hector garcia,penguin,penguin random house,general books,NaN,NaN,NaN
2,1,the courage to be disliked how to fr...,ichiro kishimi,hardcover,390,599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,ichiro kishimi,grove atlantic,allen & unwin,NaN,NaN,personal growth - success,ichiro kishimi lives in kyoto. he wr...
3,1,12 years: my messed-up love story,chetan bhagat,paperback,260,399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,chetan bhagat,harpercollins publishers india,harpercollins publishers india,NaN,NaN,general,from india's top-selling writer chet...
4,1,the mountain is you: transforming se...,brianna wiest,paperback,260,399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,brianna wiest,manjul publishing,amaryllis,NaN,NaN,body mind and spirit,this is a book about self-sabotage. ...

In [916]:
df.info()

<class 'pandas.DataFrame'>
Index: 944 entries, 0 to 944
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   944 non-null    int64
 1   title                  944 non-null    str
 2   writer                 944 non-null    str
 3   format                 928 non-null    str
 4   actual_price           944 non-null    int64
 5   price_before_discount  944 non-null    int64
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
 9   author                 938 non-null    str
 10  publisher              943 non-null    str
 11  publisher_imprint      943 non-null    str
 12  subject                91 non-null     str
 13  subject_description    27 non-null     str
 14  bisac                  408 non-null    str
 15  bisac_description      258 non-null    str
dtypes: float64(2), int64(3), str(11)
memory usage: 157.7 KB

In [917]:
df.describe()

             page  actual_price  price_before_discount  discount_percent      stars
count  944.000000    944.000000             944.000000        944.000000  14.000000
mean     8.377119    507.315678             770.468220         34.587924   4.535714
std      4.550849    444.144713             644.326945          3.795781   0.970018
min      1.000000     65.000000              99.000000          5.000000   2.000000
25%      4.000000    325.000000             499.000000         35.000000   5.000000
50%      8.000000    390.000000             599.000000         35.000000   5.000000
75%     12.000000    520.000000             799.000000         35.000000   5.000000
max     16.000000   5916.000000            7910.000000         43.000000   5.000000

In [918]:
df.nlargest(10, "actual_price")[
    ["title", "actual_price", "price_before_discount", "discount_percent"]
]

                                       title  actual_price  price_before_discount  discount_percent
636   a game of thrones: the story continues          5916                   7910              25.0
542         the chronicles of narnia box set          4731                   6712              30.0
725                the mahabharata (box set)          3575                   5500              35.0
874  vegetables: the indian way: a defini...          3574                   5200              31.0
813                  berserk deluxe volume 1          3445                   5299              35.0
79   harry potter box set: the complete c...          3250                   4999              35.0
333  diary of a wimpy kid boxset 15 books...          3250                   4999              35.0
803  5 lb. book of gre practice problems:...          3157                   3920              19.0
768                    shatter me collection          2730                   4199              35.0
346  alchemised: (english edition) the gl...          2688                   2860               6.0

In [919]:
df.drop(columns=["author"], inplace=True)

In [920]:
df["format"] = df["format"].fillna("unknown")

In [921]:
df["publisher"] = df["publisher"].fillna("unknown publisher")

In [922]:
df["publisher_imprint"] = df["publisher_imprint"].fillna("unknown publisher imprint")

In [923]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,publisher,publisher_imprint,subject,subject_description,bisac,bisac_description
0,1,atomic habits (lead title),"clear, james",paperback,650,999,35.0,3.5,• Author(s): Clear | James • Publish...,penguin,penguin random house,general books,NaN,NaN,NaN
1,1,ikigai,hector garcia,hardcover,390,599,35.0,NaN,• Author(s): Hector Garcia • Publish...,penguin,penguin random house,general books,NaN,NaN,NaN
2,1,the courage to be disliked how to fr...,ichiro kishimi,hardcover,390,599,35.0,5.0,• Author(s): Ichiro Kishimi • Publis...,grove atlantic,allen & unwin,NaN,NaN,personal growth - success,ichiro kishimi lives in kyoto. he wr...
3,1,12 years: my messed-up love story,chetan bhagat,paperback,260,399,35.0,NaN,• Author(s): Chetan Bhagat • Publish...,harpercollins publishers india,harpercollins publishers india,NaN,NaN,general,from india's top-selling writer chet...
4,1,the mountain is you: transforming se...,brianna wiest,paperback,260,399,35.0,NaN,• Author(s): Brianna Wiest • Publish...,manjul publishing,amaryllis,NaN,NaN,body mind and spirit,this is a book about self-sabotage. ...

In [924]:
drop_cols = ["bullet_9", "subject_description", "bisac_description"]

public_df = df.drop(columns=drop_cols, errors="ignore").copy()

public_df.to_csv("atlantic_books_public.csv", index=False)

print("Original columns:", df.shape[1])
print("Public columns:", public_df.shape[1])
print(public_df.columns.tolist())

Original columns: 15
Public columns: 12
['page', 'title', 'writer', 'format', 'actual_price', 'price_before_discount', 'discount_percent', 'stars', 'publisher', 'publisher_imprint', 'subject', 'bisac']

In [925]:
public_df.head()

   page                                    title          writer     format  actual_price  price_before_discount  discount_percent  stars                       publisher               publisher_imprint        subject                      bisac
0     1               atomic habits (lead title)    clear, james  paperback           650                    999              35.0    3.5                         penguin            penguin random house  general books                        NaN
1     1                                   ikigai   hector garcia  hardcover           390                    599              35.0    NaN                         penguin            penguin random house  general books                        NaN
2     1  the courage to be disliked how to fr...  ichiro kishimi  hardcover           390                    599              35.0    5.0                  grove atlantic                   allen & unwin            NaN  personal growth - success
3     1        12 years: my messed-up love story   chetan bhagat  paperback           260                    399              35.0    NaN  harpercollins publishers india  harpercollins publishers india            NaN                    general
4     1  the mountain is you: transforming se...   brianna wiest  paperback           260                    399              35.0    NaN               manjul publishing                       amaryllis            NaN       body mind and spirit

In [926]:
public_df.info()

<class 'pandas.DataFrame'>
Index: 944 entries, 0 to 944
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   944 non-null    int64
 1   title                  944 non-null    str
 2   writer                 944 non-null    str
 3   format                 944 non-null    str
 4   actual_price           944 non-null    int64
 5   price_before_discount  944 non-null    int64
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   publisher              944 non-null    str
 9   publisher_imprint      944 non-null    str
 10  subject                91 non-null     str
 11  bisac                  408 non-null    str
dtypes: float64(2), int64(3), str(7)
memory usage: 128.2 KB