#**Data Analysis in Book Trend**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df= pd.read_csv('books.csv')
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,url,bullet_1,...,bullet_3,bullet_4,bullet_5,bullet_6,bullet_7,bullet_8,bullet_9,bullet_10,bullet_11,bullet_12
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,https://atlanticbooks.com/collections/bestsell...,Current price,...,Original price,Original price,(-35%),Current price,|,/,(2),• Author(s): Clear | James • Publisher: Pengui...,Quick shop,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,https://atlanticbooks.com/collections/bestsell...,Current price,...,Original price,Original price,(-35%),Current price,|,/,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop,NaN,NaN
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,https://atlanticbooks.com/collections/bestsell...,Current price,...,Original price,Original price,(-35%),Current price,|,/,(1),• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details,Quick shop
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,https://atlanticbooks.com/collections/bestsell...,Current price,...,Original price,Original price,(-35%),Current price,|,/,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details,Quick shop,NaN
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,https://atlanticbooks.com/collections/bestsell...,Current price,...,Original price,Original price,(-35%),Current price,|,/,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details,Quick shop,NaN

In [7]:
df.drop(columns=['url'], inplace=True)

In [8]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_1,bullet_2,bullet_3,bullet_4,bullet_5,bullet_6,bullet_7,bullet_8,bullet_9,bullet_10,bullet_11,bullet_12
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,(2),• Author(s): Clear | James • Publisher: Pengui...,Quick shop,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop,NaN,NaN
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,(1),• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details,Quick shop
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details,Quick shop,NaN
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,Current price,Original price,Original price,Original price,(-35%),Current price,|,/,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details,Quick shop,NaN

In [9]:
df.drop(columns=["bullet_1", "bullet_2", "bullet_3", "bullet_4", "bullet_5", "bullet_6","bullet_7", "bullet_8"], inplace=True)

In [10]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,bullet_10,bullet_11,bullet_12
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,(2),• Author(s): Clear | James • Publisher: Pengui...,Quick shop,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop,NaN,NaN
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,(1),• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details,Quick shop
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details,Quick shop,NaN
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details,Quick shop,NaN

In [21]:
df[~df["bullet_12"].isna()]

Empty DataFrame
Columns: [page, title, writer, format, actual_price, price_before_discount, discount_percent, stars, bullet_9, bullet_10, bullet_11, bullet_12]
Index: []

In [23]:
mask = df["bullet_12"].notna()

df.loc[mask, "bullet_9"] = df.loc[mask, "bullet_10"]
df.loc[mask, "bullet_10"] = df.loc[mask, "bullet_11"]
df.loc[mask, "bullet_11"] = df.loc[mask, "bullet_12"]
df.loc[mask, "bullet_12"] = None

In [24]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,bullet_10,bullet_11,bullet_12
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,(2),• Author(s): Clear | James • Publisher: Pengui...,Quick shop,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop,NaN,NaN
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details,Quick shop,NaN
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details,Quick shop,NaN
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details,Quick shop,NaN

In [29]:
df["bullet_12"].isna().sum()

np.int64(945)

In [30]:
df.size

11340

In [31]:
df.shape

(945, 12)

In [32]:
df.drop(columns=["bullet_12"], inplace=True)

In [33]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,bullet_10,bullet_11
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,(2),• Author(s): Clear | James • Publisher: Pengui...,Quick shop
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop,NaN
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details,Quick shop
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details,Quick shop
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details,Quick shop

In [35]:
df["bullet_11"].value_counts()

bullet_11
Quick shop    528
Name: count, dtype: int64

In [37]:
df["bullet_11"].isnull().sum()

np.int64(417)

In [38]:
df.drop(columns=["bullet_11"], inplace=True)

In [39]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,bullet_10
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,(2),• Author(s): Clear | James • Publisher: Pengui...
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details

In [41]:
df["bullet_10"].value_counts()

bullet_10
View full details                                                                                                                                                      514
Quick shop                                                                                                                                                             416
• Author(s): J. K. Rowling • Publisher: Bloomsbury Publishing PLC • Publisher Imprint: Bloomsbury Publishing PLC                                                         3
• Author(s): Blyton, Enid • Publisher: Hachette Childrens Group • Publisher Imprint: Hodder Children'S Books                                                             2
• Author(s): Clear | James • Publisher: Penguin • Publisher Imprint: Penguin Random House • Subject: General Books                                                       1
• Author(s): Satoshi Yagisawa • Publisher: Bonnier Books Ltd • Publisher Imprint: Bonnier Books Ltd                                                                      1
• Author(s): Kun (UNESCO-IHE Institute for Water Education, Delft, The Netherlands) Yan • Publisher: Simon & Schuster Ltd • Publisher Imprint: Simon & Schuster Ltd      1
• Author(s): Ladybird • Publisher: Penguin Random House Children's UK • Publisher Imprint: Penguin Random House Children's UK                                            1
• Author(s): Rick Riordan • Publisher: MIXGD • Publisher Imprint: MIXGD • Subject: Children Books                                                                        1
• Author(s): Brandon Sanderson • Publisher: Orion Publishing Co • Publisher Imprint: Orion Publishing Co • BISAC: Fantasy - Contemporary                                 1
• Author(s): Jennifer Lynn Barnes • Publisher: Hachette Children's Group • Publisher Imprint: Hachette Children's Group                                                  1
• Author(s): Lauren Roberts • Publisher: Simon & Schuster Ltd • Publisher Imprint: Simon & Schuster Ltd                                                                  1
• Author(s): Tahereh Mafi • Publisher: HarperCollins Publishers • Publisher Imprint: HarperCollins Publishers • BISAC: Action & Adventure - General                      1
Name: count, dtype: int64

In [42]:
mask = df["bullet_10"].str.contains("author", case=False, na=False)

df.loc[mask, "bullet_9"] = df.loc[mask, "bullet_10"]
df.loc[mask, "bullet_10"] = None

In [43]:
df["bullet_10"].value_counts()

bullet_10
View full details    514
Quick shop           416
Name: count, dtype: int64

In [44]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9,bullet_10
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publisher: Pengui...,NaN
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...,Quick shop
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publisher: GROVE...,View full details
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...,View full details
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...,View full details

In [45]:
df.drop(columns=["bullet_10"], inplace=True)

In [46]:
df.head()

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publisher: Pengui...
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publisher: GROVE...
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...

In [47]:
df

,page,title,writer,format,actual_price,price_before_discount,discount_percent,stars,bullet_9
0,1,Atomic Habits (Lead Title),"Clear, James",Paperback,₹650,₹999,35.0,3.5,• Author(s): Clear | James • Publisher: Pengui...
1,1,Ikigai,Hector Garcia,Hardcover,₹390,₹599,35.0,NaN,• Author(s): Hector Garcia • Publisher: Pengui...
2,1,The Courage To Be Disliked How To Free Yoursel...,Ichiro Kishimi,Hardcover,₹390,₹599,35.0,5.0,• Author(s): Ichiro Kishimi • Publisher: GROVE...
3,1,12 Years: My Messed-up Love Story,Chetan Bhagat,Paperback,₹260,₹399,35.0,NaN,• Author(s): Chetan Bhagat • Publisher: Harper...
4,1,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,Paperback,₹260,₹399,35.0,NaN,• Author(s): Brianna Wiest • Publisher: Manjul...
...,...,...,...,...,...,...,...,...,...
940,16,Anansi Helps a Friend: Read It Yourself - Leve...,Ladybird,Hardcover,₹228,₹350,35.0,NaN,• Author(s): Ladybird • Publisher: Ladybird • ...
941,16,The Brothers Karamazov: A Novel in Four Parts ...,Fyodor Dostoyevsky,Paperback,₹390,₹599,35.0,5.0,• Author(s): Fyodor Dostoyevsky • Publisher: P...
942,16,The Count of Monte Cristo,Alexandre Dumas Pere,Paperback,₹390,₹599,35.0,NaN,• Author(s): Alexandre Dumas Pere • Publisher:...
943,16,Vishnu Purana,Bibek Debroy,Paperback,₹390,₹599,35.0,NaN,• Author(s): Bibek Debroy • Publisher: India P...
944,16,Food Intelligence: A comprehensive book on foo...,PhD Kevin Hall,Paperback,₹520,₹799,35.0,NaN,• Author(s): PhD Kevin Hall • Publisher: Headl...

In [49]:
df["bullet_9"].value_counts()

bullet_9
• Author(s): Shannon Messenger • Publisher: Simon & Schuster Ltd • Publisher Imprint: Simon & Schuster Ltd                                                                                                                                                   7
• Author(s): Tahereh Mafi • Publisher: HarperCollins Publishers • Publisher Imprint: HarperCollins Publishers                                                                                                                                                6
• Author(s): J. K. Rowling • Publisher: Bloomsbury Publishing PLC • Publisher Imprint: Bloomsbury Publishing PLC                                                                                                                                             5
• Author(s): Julia Donaldson • Publisher: Pan Macmillan • Publisher Imprint: Pan Macmillan                                                                                                                                                                   5
• Author(s): Ladybird • Publisher: Penguin Random House Children's UK • Publisher Imprint: Penguin Random House Children's UK                                                                                                                                5
                                                                                                                                                                                                                                                            ..
• Author(s): Ladybird • Publisher: Ladybird • Publisher Imprint: Ladybird • BISAC: Readers - BeginnerBased on Anansi the spider folktales from West Africa and the Caribbean. Anansi's children want to play with their friends, but the parents do no...    1
• Author(s): Fyodor Dostoyevsky • Publisher: Penguin • Publisher Imprint: Penguin • Subject: Creative Writing, Fiction • BISAC: ClassicsFyodor Dostoyevsky's powerful meditation on faith, meaning and morality, The Brothers Karamazov is translated ...    1
• Author(s): Alexandre Dumas Pere • Publisher: Penguin Books • Publisher Imprint: Penguin Books • BISAC: ClassicsAlexandre Dumas's epic tale of suffering and retribution, inspired by a real-life case of wrongful imprisonment--nominated as one of ...    1
• Author(s): Bibek Debroy • Publisher: India Penguin Classics • Publisher Imprint: India Penguin Classics • BISAC: Hinduism - HistoryLORD VISHNU AND THE CREATION The Vishnu Purana is part of a series of eighteen sacred Hindu texts known collectiv...    1
• Author(s): PhD Kevin Hall • Publisher: Headline Publishing Group • Publisher Imprint: Headline Publishing Group • BISAC: Diet & Nutrition - Nutrition                                                                                                      1
Name: count, Length: 869, dtype: int64

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   page                   945 non-null    int64
 1   title                  945 non-null    str
 2   writer                 945 non-null    str
 3   format                 929 non-null    str
 4   actual_price           945 non-null    str
 5   price_before_discount  944 non-null    str
 6   discount_percent       944 non-null    float64
 7   stars                  14 non-null     float64
 8   bullet_9               944 non-null    str
dtypes: float64(2), int64(1), str(6)
memory usage: 66.6 KB